### ISSUE TITLE
[Feature Request] Allow a canvas fade to an image instead of a color

### ISSUE THREAD

**Issue by spindocks** [xaukael/canvas-fade-in-out#1]
As the title says, The ability to fade to an image would add a lot of utility, allowing you to do many things like make a jumpscare image or a fade to ""cutscene"" image, or just a flashier fade to black image than just black.

If this is already possible, I would love to know how!

**Comment by xaukael** [comment]
Not at home to test, but try passing something like this: 
`await game.settings.set('canvas-fade-in-out', 'background', 'black url("https://img.freepik.com/free-vector/hand-painted-watercolor-pastel-sky-background_23-2148902771.jpg?w=1480&t=st=1689624060~exp=1689624660~hmac=3b039108612018269e005063e73ab5d69297eb6f9d34b7ef7a8034a1b20e6d08") no-repeat fixed center' )`

**Comment by spindocks** [comment]
Seems to work, thank you so much!

**Comment by xaukael** [comment]
It is just setting background CSS style on the body, so googling a bit should help you figure out how to do what you want.

**Comment by spindocks** [comment]
I believe I've mastered this issue now, but I come with a far stupider(?) one.
Is it possible to have it fade _only_ to an image, and not a color around an image? All attempts I've had resulted in it showing an image surrounded by gray. And maybe a way to change an image randomly akin to a wildcard token (this seems impossible from my small knowledge of coding.)

I think the utility in this is in adding a sort of "overlay effect" to a scene you can control via macros. Different overlays, different images. 

I'm a very new foundry user of only about 2-3 months, and I have no experience with any coding language whatsoever. I aspire to make very niche and strange games and with that comes very niche and strange requests, i guess, lol.

**Comment by xaukael** [comment]
What would be around the image then? Or are you wanting it to fill the screen?

**Comment by spindocks** [comment]
> What would be around the image then? Or are you wanting it to fill the screen?

well i was thinking it could be replaced by nothing, just be transparent and have the image appear. filling the screen could be useful, but  it does that already with a large enougu image right?

**Comment by xaukael** [comment]
like not hiding the canvas at all?

**Comment by spindocks** [comment]
> like not hiding the canvas at all?

yeah; not hiding the canvas, but displaying an image. So you could press a macro and immediately display an image overlay superimposed over the canvas map.

**Comment by xaukael** [comment]
that is out of the scope of this module. Use Narrator Tools and `/narrate <img src="file/path.png">`

**Comment by spindocks** [comment]
Hello. I have been playing around with this since we last spoke, and I had a way to change the scale, size, or zoom of an image with percentages, and now I lost that knowledge. Furthermore, all the research I've done has not helped at all. As a last ditch effort, I'm here again to ask how in all of hell do I do this again. I'm pretty sure it was sort of like this: '#646464 url("img.png")no-repeat fixed center zoom(10%)', but i can not remember the specifics and every avenue I see online does not work or apply within foundry, unless I'm just screwing it up.

**Comment by xaukael** [comment]
I am fairly certain zoom is not valid css.
Foundry's body does seem to be a bit different than expected causing center to not work quite as expected. 
I found that this sort of works.
```js
$('body').css({
  background:'no-repeat url("https://5etools-mirror-1.github.io/img/adventure/DIP/014-map-db-pc.jpg"), #111 ',
  'background-size': '50%' ,
  'background-position': 'center 100px' 
})
```

**Comment by spindocks** [comment]
Thank you for the reply. I apologize but I am very, very code ignorant, so I am looking at this that you've sent here and going "...how do i implement this :D".

The strange thing is that I vividly remember adding a modifier akin to "no-repeat", "fixed" and "center" that would allow me to alter the zoom or scale or size in SOME way. This issue arises because if I have images of 1000px x 1000px, they will be their full size, but if I have pictures of 1080px x 1920px, they will shrink, and from my (very small and very silly) experience, "fit" and "cover" (two css "modifiers" ive experiemented with) do nothing to fix that.

Thank you for responding, I'm going to keep looking for a solution, meanwhile awaiting the possibility of yours!

**Comment by xaukael** [comment]
I just updated the module. Now if there is a semicolon in the background setting, it will apply the whole string as a style to the body. So you can set many properties and thus modify the background size like this: 
```js
await game.settings.set('canvas-fade-in-out', 'background', 'background:no-repeat url("https://5etools-mirror-1.github.io/img/adventure/DIP/014-map-db-pc.jpg"), #111 ; background-size: 50%; background-position: center 200px ;')
```

**Comment by spindocks** [comment]
Thank you so much for your update, I really appreciate it!

**Comment by spindocks** [comment]
Just an added question; will all scripts need to be retypes in this fashion? When testing it out it seemed like sometimes it would work the old way, and other times it wouldnt?

**Comment by spindocks** [comment]
https://github.com/xaukael/canvas-fade-in-out/assets/80333274/e7afe9c1-56c5-413b-9932-0f0de346ec5c


https://github.com/xaukael/canvas-fade-in-out/assets/80333274/c55f5704-c441-4bbc-9752-049adafa4108


here are some videos pasting your text in verbatim; one is the old method i've been using, the other is the new string you sent me. Sorry for the inconvenience.

(this is what 1080.png should look like:)
![1080](https://github.com/xaukael/canvas-fade-in-out/assets/80333274/267034a7-9dce-4b1a-b701-e2c49b16f184)

**Comment by xaukael** [comment]
order of operations oversight on my part. It should work now in version 1.2.1
